AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - graal.spring.demo::graal-spring-demo
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  GraalVMApiService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Runtime: provided
      CodeUri: build/libs/demo-0.1-lambda.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Tracing: Active
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /books
            Method: any

Outputs:
  MicronautNativeServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets'
    Export:
      Name: MicronautNativeServiceApi